image: node:latest

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - prettier
  - lint
  - test
  - build

Prettier:
  stage: prettier
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - yarn prettier

Lint:
  stage: lint
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - yarn lint

Test:
  stage: test
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - yarn test

Build:
  stage: build
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - yarn build
