image: node:latest

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - prettier
  - lint
  - test

Prettier:
  stage: prettier
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - yarn run prettier

Lint:
  stage: lint
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - yarn run lint

Test:
  stage: test
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - yarn run test
