dist: trusty
language: node_js
node_js:
  - "12.13.1"
cache:
  yarn: true
  directories:
    - node_modules
stages:
  - Validate
  - Release
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
  - export PATH="$HOME/.yarn/bin:$PATH"
jobs:
  include:
    - stage: Validate
      script:
        - yarn bootstrap
        - yarn build --scope=atti-components
        - yarn build --scope=atti-components-documentation
        - yarn test
    - stage: Release Doc
      script:
        - yarn bootstrap
        - yarn build --scope=atti-components
        - yarn build --scope=atti-components-documentation
        - chmod +x ./scripts/deploy_doc.sh
        - ./scripts/deploy_doc.sh
