dist: trusty
language: node_js
node_js:
  - "10.16.3"
cache:
  yarn: true
  directories:
    - node_modules
stages:
  - Validate
  - Release
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
jobs:
  include:
    - stage: Validate
      script:
        - yarn install --force
        - yarn build
        - yarn test
    - stage: Release Next
      script: echo "Deploying next to npm ..."
      before_deploy:
        - "cd packages/atti-components"
        - "npm version $TRAVIS_TAG"
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_API_KEY"
        on: deploy-npm-release
        only: tags
