dist: trusty
language: node_js
node_js:
  - '12.16.1'
cache: yarn
stages:
  - Install
  - Build library
  - Build website
  - Test
  - Release
jobs:
  include:
    - stage: Install
      script: yarn install
    - stage: Build library
      before_script:
        - "cd packages/atti-components"
      script: "yarn build"
    - stage: Build website
      before_script:
        - "cd packages/website"
      script: "yarn build"
    - stage: Test
      script: yarn test
    - stage: Release Next
      script: echo "Deploying next to npm ..."
      before_deploy:
        - "cd packages/atti-components"
        - "npm version $TRAVIS_TAG"
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_API_KEY"
        on: deploy-npm-release
        only: tags
