dist: trusty
language: node_js
node_js:
  - "12.13.1"
cache:
  yarn: true
  directories:
    - node_modules
stages:
  - Validate
  - Release
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
  - export PATH="$HOME/.yarn/bin:$PATH"
jobs:
  include:
    - stage: Validate
      script:
        - yarn bootstrap
        - yarn build --scope=atti-components
        - yarn build --scope=atti-components-documentation
        - yarn test
    - stage: Release Doc
      script:
        - yarn bootstrap
        - yarn build --scope=atti-components
        - yarn build --scope=atti-components-documentation
        - "url=`curl -H \"Authorization: Bearer $NETLIFY_API_KEY\" https://api.netlify.com/api/v1/sites/atti-components/deploys`"
        - "temp=`echo $url | sed 's/\\\\\//\//g' | sed 's/[{}]//g' | awk -v k=\"text\" '{n=split($0,a,\",\"); for (i=1; i<=n; i++) print a[i]}' | sed 's/\\"\:\\"/\|/g' | sed 's/[\,]/ /g' | sed 's/\\"//g' | grep -w -m 1 'id'`"
        - "curl -X POST -H \"Authorization: Bearer $NETLIFY_API_KEY\" -d \"{}\" \"https://api.netlify.com/api/v1/sites/atti-components/deploys/${temp##*|}/restore\""
        - "curl -X POST -H \"Authorization: Bearer $NETLIFY_API_KEY\" -d \"{}\" \"https://api.netlify.com/api/v1/deploys/${temp##*|}/lock\""
